import React from 'react';

const TermsAndCondition = () => {
  return (
    <div className='w-[90%] md:w-[84%] mx-auto pb-[15%] md:pb-[5%] pt-[15%] md:pt-[5%] mb-[25%] md:mb-[15%] border-t-[3px] border-[#d9d9d9] border-b-[#d9d9d9] border-b-[3px]'>
        <div className="flex flex-col gap-[20px] lg:gap-[25px]">
         <h2 className='text-[15px] leading-[22.5px] font-bold text-center mb-[10px] md:text-[10px] md:leading-[15px] lg:text-[18px] lg:leading-[24px]'>TERMS AND CONDITIONS</h2>
         <p className='text-[10px] leading-[15px] text-justify lg:w-[80%] lg:text-[16px] lg:leading-[24px] md:text-[9px] md:leading-[13.5px]'>These Terms and Conditions ("Agreement") govern your use of the services provided by AremxyPlug Business Ent, LTD ("AremxyPlug," "we," "us," or "our"). By accessing or using our services, you ("you" or "your") agree to be bound by the terms and conditions of this Agreement. If you do not agree to these terms, please refrain from using our services.</p>
         <p className='text-[10px] leading-[15px] text-justify lg:text-[16px] lg:leading-[24px] md:text-[9px] md:leading-[13.5px]'>1. <span className='font-bold'>SERVICE DESCRIPTION: </span>AremxyPlug provides digital businesses, telecom products, payments, card issuing, digital products and services, information and communication, e-commerce, telecommunication, information and technology, VTU software, and business development services ("Services"). The description of the Services on our website or other communication channels is for informational purposes only and does not constitute a binding offer.</p>
         <div className='text-center'>
            <p className='text-[10px] leading-[15px] lg:text-[16px] lg:leading-[24px] md:text-[9px] md:leading-[13.5px] font-bold'>USER OBLIGATIONS BY USING OUR SERVICES, YOU AGREE TO:</p>
         </div>
         <div patchEvent className='flex flex-col gap-[10px]'>
            <p className='text-[10px] leading-[15px] text-justify lg:text-[16px] lg:leading-[24px] md:text-[9px] md:leading-[13.5px]'>i. <span className='font-bold'>PROVIDE ACCURATE INFORMATION: </span>You must provide accurate, complete, and up-to-date information when using our Services, including during registration and when making transactions.</p>
            <p className='text-[10px] leading-[15px] text-justify lg:text-[16px] lg:leading-[24px] md:text-[9px] md:leading-[13.5px]'>ii. <span className='font-bold'>COMPLIANCE WITH LAWS: </span>You agree to comply with all applicable laws, regulations, and third-party agreements while using our Services. You are solely responsible for ensuring that your use of our Services is lawful.</p>
            <p className='text-[10px] leading-[15px] text-justify lg:text-[16px] lg:leading-[24px] md:text-[9px] md:leading-[13.5px]'>iii. <span className='font-bold'>PROHIBITED ACTIVITIES: </span>You must not engage in any activities that are illegal, fraudulent, deceptive, malicious, or harmful to AremxyPlug or its users. Prohibited activities include, but are not limited to, unauthorized access, data scraping, hacking, distribution of malware, and any actions that violate intellectual property rights.</p>
         </div>
         <p className='text-[10px] leading-[15px] text-justify lg:text-[16px] lg:leading-[24px] md:text-[9px] md:leading-[13.5px]'>2. <span className='font-bold'>INTELLECTUAL PROPERTY: </span>All intellectual property rights related to the Services, including but not limited to trademarks, copyrights, logos, and software, belong to AremxyPlug or its licensors. You agree not to use, reproduce, modify, or distribute any intellectual property without obtaining explicit permission from the respective rights holder.</p>
         <p className='text-[10px] leading-[15px] text-justify lg:text-[16px] lg:leading-[24px] md:text-[9px] md:leading-[13.5px]'>3. <span className='font-bold'>LIMITATION OF LIABILITY: </span>To the extent permitted by applicable law, AremxyPlug and its affiliates, directors, employees, and agents shall not be liable for any direct, indirect, incidental, consequential, or exemplary damages arising from your use of the Services. This includes, but is not limited to, loss of profits, data, or business opportunities.</p>
         <p className='text-[10px] leading-[15px] text-justify lg:text-[16px] lg:leading-[24px] md:text-[9px] md:leading-[13.5px]'>4. <span className='font-bold'>TERMINATION: </span>We reserve the right to suspend or terminate your access to the Services at any time and for any reason, without prior notice or liability. Upon termination, you must immediately cease using the Services and comply with any obligations specified in this Agreement.</p>
         <p className='text-[10px] leading-[15px] text-justify lg:text-[16px] lg:leading-[24px] md:text-[9px] md:leading-[13.5px]'>5. <span className='font-bold'>MODIFICATIONS: </span>AremxyPlug may modify this Agreement from time to time at its sole discretion. We will notify you of any material changes by posting the revised Agreement on our website or sending you an email. Your continued use of the Services after the effective date of the revised Agreement constitutes your acceptance of the updated terms.</p>
         <p className='text-[10px] leading-[15px] text-justify lg:text-[16px] lg:leading-[24px] md:text-[9px] md:leading-[13.5px]'>6. <span className='font-bold'>GOVERNING LAW: </span>This Agreement shall be governed by and construed in accordance with the laws of Federal Republic of Nigeria . Any disputes arising from this Agreement shall be subject to Alternative Dispute Resolution.</p>
         <p className='text-[10px] leading-[15px] text-justify lg:text-[16px] lg:leading-[24px] md:text-[9px] md:leading-[13.5px]'>7. <span className='font-bold'>SEVERABILITY: </span>if any provision of this Agreement is deemed invalid, illegal, or unenforceable, the remaining provisions shall continue in full force and effect.</p>
         <p className='text-[10px] leading-[15px] text-justify lg:text-[16px] lg:leading-[24px] md:text-[9px] md:leading-[13.5px]'><span className='font-bold'>CONTACT INFORMATION: </span>If you have any questions, concerns, or requests regarding this Agreement, please contact us at: hello@aremxyplug.com</p>
        </div>
    </div>
  );
}

export default TermsAndCondition;
